### ISSUE TITLE
Sample of configuration file

### ISSUE THREAD

**Issue by mackermann2** [radu-stefan-dt/DDUConsumptionReporter#2]
Hi, 
I am very interested in your script to follow DDU consumption on several of our tenants (in SaaS).
But I am not able to run the script because I have no idea what the configuration file looks like.
Could you join an example in your repository of the JSON configuration file ? 
Thanks in advance and thanks a lot for your work ;)

**Comment by mackermann2** [comment]
I finally found the expected entries. The JSON configuration file below for those interested (validated on SaaS environment): 
```
{
"CLUSTER_NAME(SAAS)":{
"url":"live.dynatrace.com",
"tenant": { 
	"tenant1": "nqd25551",
	"tenant2": "csb05865",
	"tenant3": "tde95935",
	"tenant4": "drm39841",
	"tenant5": "joz54139"
},
"api_token": { 
	"tenant1":"**********",
	"tenant2":"**********",
	"tenant3":"**********",
	"tenant4":"**********",
	"tenant5":"**********"
},
"is_managed": "False"
}
} 
```

Note: I had to modify a condition in a python script request_handler.py (generate_tenant_url() function) :
(otherwise it generates an error if the key is missing in the configuration file ) 

def generate_tenant_url(cluster, tenant):
    """Generate URL based on SaaS or Managed"""
    url = HTTPS_STR
    **_if cluster["is_managed"] == "True":_**
        url += cluster['url'] + "/e/" + cluster['tenant'][tenant]
    else:
        url += cluster['tenant'][tenant] + "." + cluster['url']
    return url

**Comment by radu-stefan-dt** [comment]
Hi. This project was an early sandbox version back when DDUs were first announced. I will be deleting this repository as I do not consider the work in its current state to be as relevant anymore. Dynatrace has much more capability for such reporting now via the dedicated Billing metrics around DDUs.
